// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdfJcyXnY9pZyD9IES1ycdT_HhoZk6HtI',
    appId: '1:819889425911:web:d9b154f28bc725f9a632f2',
    messagingSenderId: '819889425911',
    projectId: 'dogg-fanpage',
    authDomain: 'dogg-fanpage.firebaseapp.com',
    databaseURL: 'https://dogg-fanpage-default-rtdb.firebaseio.com',
    storageBucket: 'dogg-fanpage.appspot.com',
    measurementId: 'G-C053HDS9Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATirpYvtFKvbsv0ZrqKxu5dxqNi5Am1ZM',
    appId: '1:819889425911:android:139a5e11ca787f5ca632f2',
    messagingSenderId: '819889425911',
    projectId: 'dogg-fanpage',
    databaseURL: 'https://dogg-fanpage-default-rtdb.firebaseio.com',
    storageBucket: 'dogg-fanpage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArJqYnL7N69TUL11JTbQ_JY4w0KYYDCN8',
    appId: '1:819889425911:ios:a985a6fb5dd3b850a632f2',
    messagingSenderId: '819889425911',
    projectId: 'dogg-fanpage',
    databaseURL: 'https://dogg-fanpage-default-rtdb.firebaseio.com',
    storageBucket: 'dogg-fanpage.appspot.com',
    androidClientId: '819889425911-i1vcia6b8kj191m6mjng69jccfkij097.apps.googleusercontent.com',
    iosClientId: '819889425911-p4o6nfl6emecoujarcogls644pkerkq6.apps.googleusercontent.com',
    iosBundleId: 'com.mdsdc.fanpageapp',
  );
}
